### ISSUE TITLE
ppati referenced before assignment

### ISSUE THREAD

**Issue by biboc** [LudwigKnuepfer/otm#1]
I try these command:
python otm.py app.elf
Traceback (most recent call last):
  File "otm.py", line 307, in <module>
    elf = parse_elf(**vars(args))
  File "otm.py", line 216, in parse_elf
    if ppati and not re.search(ppati, pathname):
UnboundLocalError: local variable 'ppati' referenced before assignment

Did I do something wrong?

**Comment by LudwigKnuepfer** [comment]
@bapclenet Which python version do you use?
otm is incompatible with python3 at the moment.

**Comment by biboc** [comment]
Python 2.7.6
On Ubuntu 14.04

**Comment by LudwigKnuepfer** [comment]
Does this help?

``` diff
diff --git a/otm.py b/otm.py
index 708ab19..631b09e 100755
--- a/otm.py
+++ b/otm.py
@@ -212,6 +212,8 @@ def parse_elf(filename, minimum_size=None, symbol_type_list=None,
         else:
             ppat = None
             npat = None
+            ppati = None
+            ppate = None

         if ppati and not re.search(ppati, pathname):
             continue
```

**Comment by biboc** [comment]
See the PR #2
